### ISSUE TITLE
Incompatibilité entre licence et but recherché

### ISSUE THREAD

**Issue by breard-r** [tromand/NeoSens#1]
Le document présenté sur ce dépôt dispose une licence extrêmement restrictive qui me semble incompatible avec sa publication même :

> Toute reproduction, représentation, utilisation ou modification est interdite
> sans l'accord de l'auteur.

Si toute reproduction est interdite, il est interdit de télécharger ce document ou de cloner ce dépôt. L'interdiction de toute utilisation viens parachever cette interdiction de téléchargement. L'interdiction de modification interdit de soumettre des pull-request afin d'améliorer le document.

Cette licence d'utilisation me semble remettre totalement en question la publication même du dit document qui devrais du coup rester privé vu que personne n'a le droit ni de se le procurer ni de l'utiliser. On est également en droit de se demander si cette licence est là par erreur, par exemple par la réutilisation d'un modèle de document, ou si c'est la publication de ce document qui est une erreur.

Dans le cas où ce serait l'apposition de cette licence particulièrement restrictive qui soit une erreur, je propose de la remplacer par une des licences [Creative Commons](https://creativecommons.org/licenses/?lang=fr). Les licences Creative Commons ont été spécialement créées afin de publier des documents de manière libre mais en conservant cependant certaines limites [définies par l'auteur](https://creativecommons.org/choose/?lang=fr).

**Comment by tromand** [comment]
Je rappelle qu'il suffit de me demander la permission.

**Comment by seirl** [comment]
Non, il ne suffit pas de demander, il faut avoir  l'accord. Vu la licence, il n'est même pas possible de voir le document puisque ça correspondrait à le télécharger, donc de le reproduire.

**Comment by tromand** [comment]
Effectivement, en plus de demander la permission , il faut respecter la réponse de l'auteur. Je comprends votre difficulté.
